########################################
# Basic Configuration
########################################
theme_version_check: true
theme_config_check: true
# main menu navigation
# for more icon information, please visit https://github.com/D-Sketon/hexo-theme-reimu/issues/30
menu:
  - name: home
    url: /
    icon: f015
  - name: archives
    url: /archives
    icon: f07c
  - name: about
    url: /about
    icon: f2bd
  - name: friend
    url: /friend
    icon: f0c0

banner: "/images/banner.webp" # which means themes/reimu/source/images/banner.webp
# You can also write it in the form of the following url
# banner: "https://example.com"

# If you want to use the srcset attribute, please enable it
banner_srcset:
  enable: false
  srcset:
    - src: "/images/banner-600w.webp"
      media: "(max-width: 479px)"
    - src: "/images/banner-800w.webp"
      media: "(max-width: 799px)"
    - src: "/images/banner.webp"
      media: "(min-width: 800px)"

favicon: "/images/favicon.ico" # which means themes/reimu/source/images/favicon.ico
# You can also write it in the form of the following url
# favicon: "https://example.com"

avatar: "avatar.webp" # which means source/_data/avatar/avatar.webp

# Control the display of the post cover
# If not set, the banner image will be displayed by default
# Its priority is lower than the cover in the Front-matter
cover: # https://example.com / false / rgb(255,117,117)

# Control the display of the post toc
# Its priority is lower than the toc in the Front-matter
toc: true
toc_options:
  list_number: true
  min_depth: 1
  max_depth: 6

# Open Graph
# see https://hexo.io/docs/helpers#open-graph
open_graph:
  enable: true
  options:
    #twitter_card: <twitter:card>
    #twitter_id: <twitter:creator>
    #twitter_site: <twitter:site>
    #twitter_image: <twitter:image>
    #google_plus: <g+:profile_link>
    #fb_admins: <fb:admin_id>
    #fb_app_id: <fb:app_id>
    default_og_image: /images/banner.webp # the default og:image for Open Graph, support absolute path

# Content
excerpt_link: Read More

# RSS
# need https://github.com/hexojs/hexo-generator-feed
rss: atom.xml

# Footer copyright
copyright: # Inject code snippet right in the footer copyright
# Need help choosing? Please see...
# https://creativecommons.org/choose/
# https://choosealicense.com/
# copyright: |-
#   <div style="flex-direction:column;align-items: center;"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></div>

footer:
  since: 2026
  powered: true
  count: true # 顯示字數和閱讀時間
  busuanzi: true
  icon:
    url: "../images/taichi.svg" # 此路徑相對於 css/style.css，因此需要向上一層到達 images 資料夾
    rotate: true
    mask: true

# Sidebar
# sidebar: right # deprecated, use sidebar.position instead
sidebar:
  position: left
  menu: true  # whether to show the sidebar menu button, ignored on mobile devices
  article:
    show_common: true # whether to show common sidebar, ignored on mobile devices

social:
  email: mailto:me@itousouta15.tw
  github: https://github.com/itousouta15
  instagram: https://www.instagram.com/itou.souta15
  discord: https://discord.gg/GVhwRRVJ7F

widgets:
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# Widget behavior
archive_type: "monthly"
show_count: false
tag_limits:
recent_posts_limits: 5
tagcloud_limits:

# Archive behavior
only_show_capsule_in_index: false # If you have hugo amounts of tags and categories, you can set this to true to only show the capsule in the index page for better performance
uppercase_capsule: true # If you want to keep taxonomic capsule unchanged, please set this to false

show_update_time: false # If you want to show the update time, please set this to true

# Summary content
summary:
  enable: false
  style: 'subtitle' # 'subtitle' or 'blockquote'

# Internationalization
i18n:
  enable: true
  type: [page, post]
  generator: [archive, category, tag, index]
  languages: [zh-TW, en]

########################################
# CSS
########################################
anchor_icon:

triangle_badge:
  enable: false
  icon: github # same as the icon in the social config
  link: https://github.com/D-Sketon/hexo-theme-reimu

layout:
  max_width: 1350px # the max width of the main content area

reimu_cursor:
  enable: true
  cursor:
    default: ../images/cursor/1.png  # 此路徑相對於 css/style.css，因此需要向上一層到達 images 資料夾
    pointer: ../images/cursor/2.png
    text: ../images/cursor/3.png

# set to false to enable fontawesome
icon_font: false

# Font loading strategy
# Custom Font -> Google Fonts -> Local FallBack Font

# Custom Font
custom_font:
  enable: false
  article:
    # - css: https://fontsapi.zeoseven.com/292/main/result.css
      # name: LXGW WenKai
  code:

# https://fonts.google.com/
# Google Fonts, higher priority than local_font
font:
  enable: true
  article:
    - Mulish
    - Noto Serif SC
  code:
    # - Ubuntu Mono
    # - Source Code Pro
    # - JetBrains Mono

# Local FallBack Font
local_font:
  article:
    - "-apple-system"
    - PingFang SC
    - Microsoft YaHei
    - sans-serif
  code:
    - Menlo
    - Monaco
    - Consolas
    - monospace

dark_mode:
  # true means that the dark mode is enabled by default
  # false means that the dark mode is disabled by default
  # auto means that the dark mode is automatically switched according to the system settings
  enable: ture # true | false | auto

########################################
# Markdown Display
########################################

# need https://github.com/D-Sketon/hexo-renderer-markdown-it-plus
math:
  enable: true 
  katex:
    enable: false
    autoRender: true 
  mathjax:
    enable: true
    options: # 參見 https://docs.mathjax.org/en/latest/web/configuration.html
      {
        tex: {
          tags: "ams",
          useLabelIds: true,
          inlineMath: [["$", "$"], ['\\(', '\\)']],
          displayMath: [["$$", "$$"], ['\\[', '\\]']],
          processEscapes: true,
          processEnvironments: true,
          autoload: { color: [], colorv2: ["color"] },
          packages: { "[+]": ["noerrors"] },
        },
        options:
          {
            skipHtmlTags:
              ["script", "noscript", "style", "textarea", "pre", "code"],
            ignoreHtmlClass: "tex2jax_ignore",
            processHtmlClass: "tex2jax_process",
          },
        loader: { load: ["input/asciimath", "[tex]/noerrors"] },
      }

# mermaid url https://github.com/mermaid-js/mermaid
# need https://github.com/webappdevelp/hexo-filter-mermaid-diagrams
mermaid:
  enable: true
  zoom: false # whether to enable zoom for mermaid diagrams

code_block:
  # whether to expand the code block by default
  # true means expand all code blocks by default
  # false means collapse all code blocks by default
  # number means collapse the code block by default when the number of lines exceeds the specified value
  expand: true

# Clipboard configuration
clipboard:
  success:
    en: Copy successfully (*^▽^*)
    zh-CN: 复制成功 (*^▽^*)
    zh-TW: 複製成功 (*^▽^*)
    ja: コピー成功 (*^▽^*)
    pt-BR: Copiado com sucesso (*^▽^*)
  fail:
    en: Copy failed (ﾟ⊿ﾟ)ﾂ
    zh-CN: 复制失败 (ﾟ⊿ﾟ)ﾂ
    zh-TW: 複製失敗 (ﾟ⊿ﾟ)ﾂ
    ja: コピー失敗 (ﾟ⊿ﾟ)ﾂ
    pt-BR: Falha ao copiar (ﾟ⊿ﾟ)ﾂ
  copyright: # whether to add a copyright for the clipped content
    enable: false
    count: 50 # The number of characters when the copyright is displayed
    license_type: by-nc-sa # https://creativecommons.org/licenses

########################################
# Analytics
########################################

baidu_analytics: false
google_analytics: false
clarity: false

########################################
# Comment system
########################################

waline:
  enable: true # 修正拼寫錯誤
  serverURL: https://web-eight-weld-65.vercel.app
  lang: zh-TW
  locale: {} # https://waline.js.org/guide/features/i18n.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80
  emoji:
    - https://unpkg.com/@waline/emojis@1.2.0/weibo
    - https://unpkg.com/@waline/emojis@1.2.0/alus
    - https://unpkg.com/@waline/emojis@1.2.0/bilibili
    - https://unpkg.com/@waline/emojis@1.2.0/qq
    - https://unpkg.com/@waline/emojis@1.2.0/tieba
    - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
  meta:
    - nick
    - mail
    - link
  requiredMeta:
    - nick
    - mail
  wordLimit: 0
  pageSize: 10
  pageview: true

########################################
# Search
########################################

# need https://github.com/D-Sketon/hexo-algoliasearch
# please add the following config in your _config.yml
# algolia:
#   appId: 'your applicationID'
#   apiKey: 'your apiKey'
#   adminApiKey: 'your adminApiKey'
#   indexName: 'your indexName'
#   chunkSize: 5000
#   fields:
#     - content:strip:truncate,0,500
#     - excerpt:strip
#     - gallery
#     - permalink
#     - photos
#     - slug
#     - tags
#     - title
algolia_search:
  enable: false
  hits:
    per_page: 10

generator_search:
  enable: false
  field: post
  content: true

########################################
# Animation
########################################

# 加載動畫
preloader:
  enable: true
  text: 載入中...
  icon:
    url: "../images/taichi.svg" # 此路徑相對於 css/style.css，因此需要向上一層到達 images 資料夾

# see https://github.com/D-Sketon/aos.js
animation:
  enable: true
  options:
    header:
      title: slide-up
      subTitle: slide-down
    home:
      post: fade-up
      widget: fade-up
      sidebar: fade-up
    article:
      whole: fade-up
      date: zoom-in
      category: zoom-in
      tag: zoom-in
      comment: zoom-in
      reading: zoom-in
      nav: fade-up
    archive:
      whole: fade-up
      tag: zoom-in
      category: zoom-in
      section: fade-up
      nav: fade-up

# see https://github.com/D-Sketon/mouse-firework
firework:
  enable: true
  disable_on_mobile: false
  options:
    excludeElements: ["a", "button"]
    particles:
      - shape: circle
        move: ["emit"]
        easing: easeOutExpo
        colors: ["var(--red-1)", "var(--red-2)", "var(--red-3)", "var(--red-4)"]
        number: 20
        duration: [1200, 1800]
        shapeOptions:
          radius: [16, 32]
          alpha: [0.3, 0.5]
      - shape: circle
        move: ["diffuse"]
        easing: easeOutExpo
        colors: ["var(--red-0)"]
        number: 1
        duration: [1200, 1800]
        shapeOptions:
          radius: 20
          alpha: [0.2, 0.5]
          lineWidth: 6

########################################
# Extended features
##########################################
# 實驗性功能
########################################

# 實驗性功能，可能有很多錯誤，請謹慎開啟！
pjax:
  enable: true

# 實驗性功能
# https://github.com/GoogleChromeLabs/quicklink
quicklink:
  enable: false
  # `requestIdleCallback` 的超時時間，以毫秒為單位。
  timeout: 3000
  # 是否應將 options.el 容器內的 URL 視為高優先級。
  priority: true
  # 確定是否應預取 URL。
  # 僅支持字符串
  ignores: []

# https://github.com/CodeByZach/pace
pace:
  enable: true

# 實驗性功能
service_worker:
  enable: true

# 實驗性功能
live2d:
  enable: false
  position: left # left or right

# 實驗性功能
# 請開啟 pjax 以使用此功能
live2d_widgets:
  enable: false

# 實驗性功能
player:
  # 如果您啟用了 meting，您必須先啟用 aplayer
  aplayer:
    # https://github.com/DIYgod/APlayer
    enable: false
    options:
      audio:
      fixed:
      autoplay:
      loop:
      order:
      preload:
      volume:
      mutex:
      listFolded:
      lrcType:
  meting:
    # https://github.com/metowolf/MetingJS
    # 如果您想使用 meting，請先啟用 aplayer
    enable: false
    meting_api: # 自定義 api
    options:
      id: 2265921590
      server: netease
      type: playlist

########################################
# 供應商
########################################

# 依賴 cdn 連結
# 如果您更改了 js 庫的版本，請務必修改相應的完整性值
vendor:
  cdn_jsdelivr_gh: https://cdn.jsdelivr.net/gh/
  cdn_jsdelivr_npm: https://cdn.jsdelivr.net/npm/
  fastly_jsdelivr_gh: https://fastly.jsdelivr.net/gh/
  fastly_jsdelivr_npm: https://fastly.jsdelivr.net/npm/
  unpkg: https://unpkg.com/
  webcache: https://npm.webcache.cn/
  js:
    clipboard:
      src: cdn_jsdelivr_npm|clipboard@2.0.11/dist/clipboard.min.js
      integrity: sha384-J08i8An/QeARD9ExYpvphB8BsyOj3Gh2TSh1aLINKO3L0cMSH2dN3E22zFoXEi0Q
    lazysizes:
      src: cdn_jsdelivr_npm|lazysizes@5.3.2/lazysizes.min.js
      integrity: sha384-3gT/vsepWkfz/ff7PpWNUeMzeWoH3cDhm/A8jM7ouoAK0/fP/9bcHHR5kHq2nf+e
    photoswipe:
      src: cdn_jsdelivr_npm|photoswipe@5.4.4/dist/photoswipe.esm.min.js
      integrity: sha384-WkkO3GCmgkC3VQWpaV8DqhKJqpzpF9JoByxDmnV8+oTJ7m3DfYEWX1fu1scuS4+s
    photoswipe_lightbox:
      src: cdn_jsdelivr_npm|photoswipe@5.4.4/dist/photoswipe-lightbox.esm.min.js
      integrity: sha384-DiL6M/gG+wmTxmCRZyD1zee6lIhawn5TGvED0FOh7fXcN9B0aZ9dexSF/N6lrZi/
    valine:
      src: cdn_jsdelivr_npm|valine@1.5.1/dist/Valine.min.js
      integrity: sha384-3ma91AExDeMAZ1rjTjaP8V2A2obQE+s5ltKRwYlwdpArz9xVbp0tF3b0VV2ACNPn
    waline:
      src: cdn_jsdelivr_npm|@waline/client@2.15.8/dist/waline.mjs
      integrity: sha384-9sbqJjrfGjbkI6/PI4nU/MvBfEmkkPC4YK9I4zBeMIf1CVCZdCMH/KinBEAZII/5
    twikoo:
      src: cdn_jsdelivr_npm|twikoo@1.6.16/dist/twikoo.all.min.js
      integrity: sha384-lDHsr5aZmkMS0eKnsUu6e9RWP+dRmn7sgjRAKGOAoXfMyzbUK6Qi86zZK7R+KvRV
    gitalk:
      src: cdn_jsdelivr_npm|gitalk@1.8.0/dist/gitalk.min.js
      integrity: sha384-kspnZUWBoSWwoJHa0hBCXYbHGbhvU/lcEH5O8eVbSDhbPwsiVUTp/aGX/z/5EuMA
    busuanzi:
      src: cdn_jsdelivr_npm|busuanzi@2.3.0/bsz.pure.mini.js
      integrity: sha384-0M75wtSkhjIInv4coYlaJU83+OypaRCIq2SukQVQX04eGTCBXJDuWAbJet56id+S
    algolia:
      src: cdn_jsdelivr_npm|algoliasearch@4.17.1/dist/algoliasearch-lite.umd.js
      integrity: sha384-xvLS0jfKuoREs7pqkRI/OI8GcqohO5S+jQz7ZBtQXnsXmD+9jDOOY4cL6dCPzlrk
    instantsearch:
      src: cdn_jsdelivr_npm|instantsearch.js@4.56.1/dist/instantsearch.production.min.js
      integrity: sha384-hHJCflT4KBLQyHfKO9vpstIcFKn/Y+KHTORelMMEn7mOp2AVPp+7fr03dLgZiV3J
    pace:
      src: cdn_jsdelivr_npm|pace-js@1.2.4/pace.min.js
      integrity: sha384-k6YtvFUEIuEFBdrLKJ3YAUbBki333tj1CSUisai5Cswsg9wcLNaPzsTHDswp4Az8
    mermaid:
      src: cdn_jsdelivr_npm|mermaid@9.4.3/dist/mermaid.min.js
      integrity: sha384-aG3Gai4tbCHF0iXo48HwLoOZyut7mBl50oMC9GD1m75xyHfJDv6w8hD/kZRD47aJ
    firework:
      src: cdn_jsdelivr_npm|mouse-firework@0.1.1/dist/index.umd.js
      integrity: sha384-8LyaidD9GPxQQgLJO/WRw/O2h3BoNq/ApI/ecpvM6RsrCz2qP2ppBXUKihP4V/2d
    pjax:
      src: cdn_jsdelivr_npm|theme-shokax-pjax@0.0.3/dist/index.umd.js
      integrity: sha384-xneY1WY8hOfUzswrE4CrYq35N4BdVcxqxwHPr9zawE/jMSCxD+jAPU55x/jj3wlf
    live2d:
      base: cdn_jsdelivr_gh|D-Sketon/plugin-live2d/
      js: cdn_jsdelivr_gh|D-Sketon/plugin-live2d/js/live2d-autoload.js
    live2d_widgets:
      src: cdn_jsdelivr_npm|live2d-widgets@0.9.0/autoload.js
      integrity: sha384-poTN7wN/SqNhQqo3jdFeX20ikddWeFGkUkDEzsKjgH/ez8aQLn81oI0Cw6q5xNyB
    md5:
      src: cdn_jsdelivr_npm|blueimp-md5@2.19.0/js/md5.min.js
      integrity: sha384-JmVtRz6RWiXnA14QbIOJzPuU3MidULOpBP66deeLLyyoF4Tr/gZlbkHkL6vTthxH
    quicklink:
      src: cdn_jsdelivr_npm|quicklink@2.3.0/dist/quicklink.umd.js
      integrity: sha384-aD7FsuQkS1ohgFKY41fJfeA+Wd/QRNnrOd9Bs58K3FzKdJJv8yPnYU8Tnp5z1agS
    katex:
      src: cdn_jsdelivr_npm|katex@0.16.11/dist/katex.min.js
      integrity: sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg
    katex_auto_render:
      src: cdn_jsdelivr_npm|katex@0.16.11/dist/contrib/auto-render.min.js
      integrity: sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk
    mathjax:
      src: cdn_jsdelivr_npm|mathjax@3.2.2/es5/tex-mml-chtml.js
      integrity: sha384-Wuix6BuhrWbjDBs24bXrjf4ZQ5aFeFWBuKkFekO2t8xFU0iNaLQfp2K6/1Nxveei
    aplayer:
      src: cdn_jsdelivr_npm|aplayer@1.10.1/dist/APlayer.min.js
      integrity: sha384-gdGYZwHnfJM54evoZhpO0s6ZF5BQiybkiyW7VXr+h5UfruuRL/aORyw+5+HZoU6e
    meting:
      src: cdn_jsdelivr_npm|meting@2.0.1/dist/Meting.min.js
      integrity: sha384-ASVlpKF80A22OXTK3tfEjZm1EL6uFMKIC4p8+0maanw1S/IyB+Y4JG+ZDU7GpKE8
    qrcode:
      src: cdn_jsdelivr_npm|qrcode@1.4.4/build/qrcode.min.js
      integrity: sha384-0RsG1yo/crf/1Qc14sho26SXXOTngNCjgJw7fuvXBt9W/OChF/Ijx+aUuBDqQwEk
    html2image:
      src: cdn_jsdelivr_npm|html-to-image@1.11.11/dist/html-to-image.js
      integrity: sha384-UbfRVKN3/elS1r7JcK2FhmPP+KlJ4CvYwbyYD7tH+uTkbT9bNJr9eJeQ0FoFbAgz
    dompurify:
      src: cdn_jsdelivr_npm|dompurify@3.2.4/dist/purify.min.js
      integrity: sha384-eEu5CTj3qGvu9PdJuS+YlkNi7d2XxQROAFYOr59zgObtlcux1ae1Il3u7jvdCSWu/
  css:
    photoswipe: cdn_jsdelivr_npm|photoswipe@5.4.4/dist/photoswipe.css
    katex: cdn_jsdelivr_npm|katex@0.16.11/dist/katex.min.css
    waline: cdn_jsdelivr_npm|@waline/client@2.15.8/dist/waline.css
    gitalk: cdn_jsdelivr_npm|gitalk@1.8.0/dist/gitalk.css
    fontawesome:
      high_priority:
        - cdn_jsdelivr_npm|@fortawesome/fontawesome-free@6.5.1/css/regular.min.css
        - cdn_jsdelivr_npm|@fortawesome/fontawesome-free@6.5.1/css/solid.min.css
      low_priority:
        - cdn_jsdelivr_npm|@fortawesome/fontawesome-free@6.5.1/css/brands.min.css
        - cdn_jsdelivr_npm|@fortawesome/fontawesome-free@6.5.1/css/v5-font-face.min.css
        - cdn_jsdelivr_npm|@fortawesome/fontawesome-free@6.5.1/css/v4-font-face.min.css
    aos: cdn_jsdelivr_npm|@reimujs/aos@0.1.0/dist/aos.css
    aplayer: cdn_jsdelivr_npm|aplayer@1.10.1/dist/APlayer.min.css
